name: Curio Bot
on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para meu hosting
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "/"
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_USER: ${{ secrets.SSH_USER }}
            TARGET: "/curio-bot"
            EXCLUDE: "/dist/, /node_modules/"
            SCRIPT_BEFORE: |
              whoami
              ls -al
            SCRIPT_AFTER: |
              whoami
              ls -al
              echo $RSYNC_STDOUT