name: Curio Bot
on:
  push: 
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: /
          scp_target: ~/curio-bot
          before_script: |
            cd curio-bot
            docker compose --env-file .env down
          after_script: |
            docker compose build
            docker compose --env-file .env up bot -d